spring:
  application:
    name: configuration-server

  profiles:
    active:
      - native
      - git

  cloud:
    config:
      server:
        git:
          uri: https://github.com/kzrv/config
        native:
          search-locations: classpath:/config

#encrypt:
#  key: secret

server:
  port: 8071